### ISSUE TITLE
problem while trying to test the code

### ISSUE THREAD

**Issue by benjamin-thiery** [wasiahmad/NeuralCodeSum#33]
Hi, 

I'm an intern trying to find the best solution to comment code automatically. 
For this i've been trying to test all existing solutions and yours came to me.

I think I've installed all the requirements. I work on a WSL with python 3.8 and I got the following error while trying to execute the code 

```
~/NeuralCodeSum/scripts/python$ bash transformer.sh 0 code2jdoc                                

============TRAINING============
Traceback (most recent call last):
File "../../main/train.py", line 675, in <module>
set_defaults(args)
File "../../main/train.py", line 153, in set_defaults
raise IOError('No such file: %s' % train_src)
OSError: No such file: ../../data/python/train/code.original_subtoken
============TESTING============
Traceback (most recent call last):                                                                                        
File "../../main/train.py", line 675, in <module>                                                                         
set_defaults(args)                                                                                                   
File "../../main/train.py", line 186, in set_defaults                                                                     
raise IOError('No such file: %s' % dev_src)                                                                         
OSError: No such file: ../../data/python/test/code.original_subtoken
============Beam Search TESTING============  
Traceback (most recent call last):
File "../../main/test.py", line 448, in <module>
set_defaults(args)
File "../../main/test.py", line 151, in set_defaults
raise IOError('No such file: %s' % dev_src)
OSError: No such file: ../../data/python/test/code.original_subtoken
```
I'm surely just dumb not to have understood the reason of this error but could u please enlighten me ?

**Comment by wasiahmad** [comment]
The error message, `No such file: ../../data/python/test/code.original_subtoken` is clear, isn't it? Please check if you have downloaded the data correctly.

**Comment by comqdhb** [comment]
Clear because the file is not there.  Unclear because the script does not always work.  The download from google drive can sometimes fail and you need to try again BUT after a period of time.
